function Hd = BandPass
%BANDPASS 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 23-Apr-2024 16:48:39

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 25000;  % Sampling Frequency

N    = 10;       % Order
Fc1  = 7000;      % First Cutoff Frequency
Fc2  = 9000;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hann(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]