function Hd = HighPass(Fc,Fs)
%HIGHPASS 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 18-Apr-2024 21:43:04

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
% Fc: Cutoff Frequency
% Fs: Sampling Frequency

N    = 16;       % Order
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'high', win, flag);
Hd = dfilt.dffir(b);

% [EOF]